import sys
from pathlib import Path
import argparse

import verifacts.load.json
import verifacts.fact.file
import verifacts.fact.anchor
import verifacts.fact.module
import verifacts.fact.macro

def main(argv):
    parser = argparse.ArgumentParser(
        prog = 'verifacts',
        description = 'Parse Verible output with Kythe facts about Verilog code and generate .md files')
    parser.add_argument('verible_json_file',
        help = 'JSON file with Kythe facts generated by Verible from Verilog source code')
    parser.add_argument('output_path',
        help = 'Location where to put all generated .md files')
    parser.add_argument('-s', '--strip-path',
        help = 'Strip common root SV source location path')
    args = parser.parse_args()

    verible_json_file = Path(args.verible_json_file)
    if not verible_json_file.exists():
        print(f"Error: file {verible_json_file} does not exist")
        exit(1)

    output_path = Path(args.output_path)
    if not output_path.exists():
        print(f"Error: directory {output_path} does not exist")
        exit(1)

    facts = verifacts.load.json.load_facts_as_json(verible_json_file)
    verifacts.load.json.facts_decode_strings(facts)
    ##for fact in facts:
    ##    print(fact)

    fact_files = verifacts.fact.file.facts_find_files(facts)
    fact_anchors = verifacts.fact.anchor.facts_find_anchors(facts)
    fact_modules = verifacts.fact.module.facts_find_modules(facts, fact_files, fact_anchors)
    fact_macros = verifacts.fact.macro.facts_find_macros(facts, fact_files, fact_anchors)

    print(f"number of SystemVerilog files is {len(fact_files)}")
    verifacts.fact.file.facts_dump_files(output_path, fact_files, args.strip_path)

    print(f"number of modules is {len(fact_modules)}")
    verifacts.fact.module.facts_dump_modules(output_path, fact_modules, args.strip_path)

    print(f"number of macros is {len(fact_macros)}")
    verifacts.fact.macro.facts_dump_macros(output_path, fact_macros, args.strip_path)

    index_md = output_path / 'index.md'
    with open(index_md, 'w', encoding="utf-8") as file:
        file.write("# Index\n\n")
        file.write("- [Files](files/list.md)\n")
        file.write("- [Modules](modules/list.md)\n")
        file.write("- [Macros](macros/list.md)\n")
