import sys
from pathlib import Path
import argparse

import verifacts.load.json
import verifacts.fact.file
import verifacts.fact.module

def main(argv):
    parser = argparse.ArgumentParser(
        prog = 'verifacts',
        description = 'Parse Verible output with Kythe facts about Verilog code and generate .md files')
    parser.add_argument('verible_json_file',
        help = 'JSON file with Kythe facts generated by Verible from Verilog source code')
    parser.add_argument('output_path',
        help = 'Location where to put all generated .md files')
    args = parser.parse_args()

    verible_json_file = Path(args.verible_json_file)
    if not verible_json_file.exists():
        print(f"Error: file {verible_json_file} does not exist")
        exit(1)

    output_path = Path(args.output_path)
    if not output_path.exists():
        print(f"Error: directory {output_path} does not exist")
        exit(1)

    facts = verifacts.load.json.load_facts_as_json(verible_json_file)
    verifacts.load.json.facts_decode_strings(facts)
    ##for fact in facts:
    ##    print(fact)

    fact_files = verifacts.fact.file.facts_find_files(facts)
    verifacts.fact.module.facts_find_modules(facts, fact_files)

    verifacts.fact.file.facts_dump_files(output_path, fact_files)

